version: "3.9"
services:
  mountebank:
    container_name: mountebank
    image: "bbyars/mountebank:2.8.1"
    ports:
      - "2525:2525"
      - "4545-4560:4545-4560"
    command:
      - "start"
    networks:
      - imposters

  sidecar-init:
    container_name: sidecar-init
    image: dockvalkyrie/mountebank-imposters:0.7.1
    networks:
      - imposters

networks:
  imposters:
    name: imposters
    external: true