name: "Mountebank Imposters UAT"

on:
  push:
    tags:
      - uat/*

env:
  REGISTRY_HUB_NAMESPACE: ${{ secrets.DOCKER_HUB_NAMESPACE }}
  REGISTRY_IMAGE_NAME: mountebank-imposters

jobs:
  deployment:
    name: 'Build and Publish Docker Image'
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Generate Docker Metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ${{ env.REGISTRY_HUB_NAMESPACE }}/${{ env.REGISTRY_IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=match, pattern=uat/v(\d.\d.\d), group=1

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_REPO_USERNAME }}
          password: ${{ secrets.DOCKER_REPO_PASSWORD }}

      - name: Build and Dry-run
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}-uat
          labels: ${{ steps.meta.outputs.labels }}